### ISSUE TITLE
连接时经常断开连接的情况

### ISSUE THREAD

**Issue by jiezhuo** [bilibilifmk/wifi_link_tool#2]
微信小程序-卒
手机连接到8266的热点,然后自动跳转到了搜索附近wifi的界面,此时手机会发现这个热点无法连接到网络,然后自动断开了连接(拦不住的那种),电脑也有一样的问题
偶尔能成功一次,原因不详

**Comment by bilibilifmk** [comment]
首先检查是否是sdk造成该问题
