### ISSUE TITLE
 sdk版本：3.0.0 运行失败

### ISSUE THREAD

**Issue by jindaxia** [bilibilifmk/wifi_link_tool#7]
什么时候可以支持 3.0的

**Comment by bilibilifmk** [comment]
更高版本的sdk意味着 需要找出所有隐性bug 目前已知 eeprom有问题  最近也很忙 我会尽快适配的 感谢你的支持

**Comment by bilibilifmk** [comment]
此case 已在 commit 30f77ce3d279080fda16574c96068f3895268f16 （v1.1.7）中修复  感谢你的支持 与反馈
