### ISSUE TITLE
有没有能够网页键入其他数据的支持计划？

### ISSUE THREAD

**Issue by vihor3** [bilibilifmk/wifi_link_tool#8]
比如可以网页输入mqtt或者其他数据，和wifi数据同时发送

**Comment by bilibilifmk** [comment]
没有太明白你表达的意思，可以详细说明吗

**Comment by Nigh** [comment]
> 比如可以网页输入mqtt或者其他数据，和wifi数据同时发送

你需要自己编写前端页面和固件的后端接口来实现定制化的功能。

**Comment by bilibilifmk** [comment]
没有表达清楚具体需求，不做处理
