### ISSUE TITLE
Some code issue 几处代码问题导致无法正常运行

### ISSUE THREAD

**Issue by Nigh** [bilibilifmk/wifi_link_tool#9]
## 1. 数值与字符串
在`wifi_link_tool.h`中，所有的`EEPROM.write`写入的均为数值，而`EEPROM.read`相关的代码使用的均为字符串。导致了启动时的判断一直为未重置的状态。修改所有`EEPROM.write`写入为字符可以修复。

## 2. delay导致crash
`blink()`函数中，等待重启之前的`delay(300);`会导致程序直接崩溃重启。删除后可以正常运行。

**Comment by bilibilifmk** [comment]
第一个case 是遗留问题会尽快修复，第二个case暂时不做处理，在以前版本的bl中第一次重启会导致莫名的卡住必须要重新上电，所以blink那个是让看门狗触发 直接对esp复位

**Comment by bilibilifmk** [comment]
此case 已在 commit 30f77ce3d279080fda16574c96068f3895268f16 （v1.1.7）中修复  感谢你的支持 与反馈
